services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      
      PGDATA: /data/postgres
      POSTGRES_DB: samsoft
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db:
